ALTER TABLE employees
ADD COLUMN IF NOT EXISTS telegram_username TEXT;

ALTER TABLE employees
ADD COLUMN IF NOT EXISTS phone_number TEXT;

ALTER TABLE employees
ADD COLUMN IF NOT EXISTS has_whatsapp BOOLEAN NOT NULL DEFAULT FALSE;
